-- ==========================================================
-- TRAGALERO: TABLAS DE TEMPLATES, MENÚS Y ÓRDENES
-- ==========================================================

/*
INSTRUCCIONES:
1. Ve a tu panel de Supabase -> SQL Editor.
2. Copia y pega todo el contenido de este archivo y haz clic en 'Run'.
3. Ve a la sección 'Database' -> 'Publications' -> 'supabase_realtime'
   y asegúrate de habilitar las tablas 'tragalero_orders' y 'menutech_orders' para actualizaciones en tiempo real.
*/

-- 1. TABLA PARA PLANTILLAS WEB (adminTemplate.html)
CREATE TABLE IF NOT EXISTS public.tragalero_web_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE UNIQUE,
    config JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.menutech_web_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE UNIQUE,
    config JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABLA PARA MENÚS DIGITALES (adminMenus.html / menu.html)
CREATE TABLE IF NOT EXISTS public.tragalero_menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE UNIQUE,
    domain TEXT,
    slug TEXT UNIQUE,
    menu_style TEXT DEFAULT 'mode2',
    cover_url TEXT,
    cover_type TEXT DEFAULT 'image',
    config JSONB DEFAULT '{"categories": [], "toppings": []}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.menutech_menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE UNIQUE,
    domain TEXT,
    slug TEXT UNIQUE,
    menu_style TEXT DEFAULT 'mode2',
    cover_url TEXT,
    cover_type TEXT DEFAULT 'image',
    config JSONB DEFAULT '{"categories": [], "toppings": []}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABLA PARA ÓRDENES EN TIEMPO REAL (adminOrders.html)
CREATE TABLE IF NOT EXISTS public.tragalero_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    client_name TEXT,
    client_phone TEXT,
    client_address TEXT,
    customer_name TEXT,
    customer_phone TEXT,
    address TEXT,
    order_type TEXT,
    reference TEXT,
    delivery_time_mode TEXT,
    delivery_date TEXT,
    delivery_time TEXT,
    payment_method TEXT,
    items JSONB DEFAULT '[]'::jsonb,
    total NUMERIC(10,2) DEFAULT 0,
    status TEXT DEFAULT 'pending', -- pending, in_progress, completed, cancelled
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.menutech_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    client_name TEXT,
    client_phone TEXT,
    client_address TEXT,
    customer_name TEXT,
    customer_phone TEXT,
    address TEXT,
    order_type TEXT,
    reference TEXT,
    delivery_time_mode TEXT,
    delivery_date TEXT,
    delivery_time TEXT,
    payment_method TEXT,
    items JSONB DEFAULT '[]'::jsonb,
    total NUMERIC(10,2) DEFAULT 0,
    status TEXT DEFAULT 'pending', -- pending, in_progress, completed, cancelled
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Asegurar columnas opcionales si las tablas ya existían antes
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS customer_name TEXT;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS customer_phone TEXT;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS order_type TEXT;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS reference TEXT;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS delivery_time_mode TEXT;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS delivery_date TEXT;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS delivery_time TEXT;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS preparing_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS ready_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS delivered_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS rejection_reason TEXT;

ALTER TABLE public.menutech_orders ADD COLUMN IF NOT EXISTS customer_name TEXT;
ALTER TABLE public.menutech_orders ADD COLUMN IF NOT EXISTS customer_phone TEXT;
ALTER TABLE public.menutech_orders ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.menutech_orders ADD COLUMN IF NOT EXISTS order_type TEXT;
ALTER TABLE public.menutech_orders ADD COLUMN IF NOT EXISTS reference TEXT;
ALTER TABLE public.menutech_orders ADD COLUMN IF NOT EXISTS delivery_time_mode TEXT;
ALTER TABLE public.menutech_orders ADD COLUMN IF NOT EXISTS delivery_date TEXT;
ALTER TABLE public.menutech_orders ADD COLUMN IF NOT EXISTS delivery_time TEXT;
ALTER TABLE public.menutech_orders ADD COLUMN IF NOT EXISTS payment_method TEXT;

-- 4. TABLA PARA MENÚS FÍSICOS (physicalMenu.html)
CREATE TABLE IF NOT EXISTS public.tragalero_physical_menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    template_id TEXT,
    layout_config JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, template_id)
);

CREATE TABLE IF NOT EXISTS public.menutech_physical_menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    template_id TEXT,
    layout_config JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, template_id)
);

-- 5. HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.tragalero_web_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menutech_web_templates ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.tragalero_menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menutech_menus ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.tragalero_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menutech_orders ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.tragalero_physical_menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menutech_physical_menus ENABLE ROW LEVEL SECURITY;

-- 6. POLÍTICAS DE ACCESO PÚBLICO / PROPIETARIO

-- Tragalero Web Templates
DROP POLICY IF EXISTS "Public tragalero web templates view" ON public.tragalero_web_templates;
CREATE POLICY "Public tragalero web templates view" ON public.tragalero_web_templates FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Owner manage tragalero web templates" ON public.tragalero_web_templates;
CREATE POLICY "Owner manage tragalero web templates" ON public.tragalero_web_templates FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- Legacy Web Templates
DROP POLICY IF EXISTS "Public web templates view" ON public.menutech_web_templates;
CREATE POLICY "Public web templates view" ON public.menutech_web_templates FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Owner manage web templates" ON public.menutech_web_templates;
CREATE POLICY "Owner manage web templates" ON public.menutech_web_templates FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- Tragalero Digital Menus
DROP POLICY IF EXISTS "Public tragalero menus view" ON public.tragalero_menus;
CREATE POLICY "Public tragalero menus view" ON public.tragalero_menus FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Owner manage tragalero menus" ON public.tragalero_menus;
CREATE POLICY "Owner manage tragalero menus" ON public.tragalero_menus FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- Legacy Digital Menus
DROP POLICY IF EXISTS "Public menus view" ON public.menutech_menus;
CREATE POLICY "Public menus view" ON public.menutech_menus FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Owner manage menus" ON public.menutech_menus;
CREATE POLICY "Owner manage menus" ON public.menutech_menus FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- Tragalero Orders
DROP POLICY IF EXISTS "Public insert tragalero orders" ON public.tragalero_orders;
CREATE POLICY "Public insert tragalero orders" ON public.tragalero_orders FOR INSERT WITH CHECK (TRUE);

DROP POLICY IF EXISTS "Owner manage tragalero orders" ON public.tragalero_orders;
CREATE POLICY "Owner manage tragalero orders" ON public.tragalero_orders FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- Legacy Orders
DROP POLICY IF EXISTS "Public insert orders" ON public.menutech_orders;
CREATE POLICY "Public insert orders" ON public.menutech_orders FOR INSERT WITH CHECK (TRUE);

DROP POLICY IF EXISTS "Owner manage orders" ON public.menutech_orders;
CREATE POLICY "Owner manage orders" ON public.menutech_orders FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- Physical Menus
DROP POLICY IF EXISTS "Owner manage tragalero physical menus" ON public.tragalero_physical_menus;
CREATE POLICY "Owner manage tragalero physical menus" ON public.tragalero_physical_menus FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

DROP POLICY IF EXISTS "Owner manage physical menus" ON public.menutech_physical_menus;
CREATE POLICY "Owner manage physical menus" ON public.menutech_physical_menus FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- 7. ACTIVAR REALTIME PARA ÓRDENES
-- 7. ACTIVAR REALTIME PARA ÓRDENES (IDEMPOTENTE)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        IF NOT EXISTS (
            SELECT 1 FROM pg_publication_tables
            WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'tragalero_orders'
        ) THEN
            ALTER PUBLICATION supabase_realtime ADD TABLE public.tragalero_orders;
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM pg_publication_tables
            WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'menutech_orders'
        ) THEN
            ALTER PUBLICATION supabase_realtime ADD TABLE public.menutech_orders;
        END IF;
    END IF;
END $$;
