-- ==========================================================
-- SETUP PARA ADMIN WEB - TRAGALERO
-- ==========================================================

-- 1. EXTENSIONES
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. FUNCIONES DE APOYO (EVITAR RECURSIVIDAD RLS)
CREATE OR REPLACE FUNCTION public.check_is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.usuarios
        WHERE id = auth.uid() AND role = 'Admin'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 3. TABLA DE USUARIOS
CREATE TABLE IF NOT EXISTS public.usuarios (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL UNIQUE,
    email TEXT UNIQUE,
    role TEXT DEFAULT 'Owner' CHECK (role IN ('Owner', 'Admin', 'Developer')),
    is_active BOOLEAN DEFAULT TRUE,
    max_businesses INTEGER DEFAULT 1,
    domain TEXT,
    gallery_type TEXT DEFAULT 'grid',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Asegurar columnas si ya existe la tabla usuarios
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='usuarios' AND column_name='email') THEN
        ALTER TABLE public.usuarios ADD COLUMN email TEXT UNIQUE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='usuarios' AND column_name='domain') THEN
        ALTER TABLE public.usuarios ADD COLUMN domain TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='usuarios' AND column_name='gallery_type') THEN
        ALTER TABLE public.usuarios ADD COLUMN gallery_type TEXT DEFAULT 'grid';
    END IF;
    -- Update role check constraint if needed (complex via SQL, typically done manually or by dropping and recreating if safe)
    -- For safety in this setup, we assume IF NOT EXISTS handles the initial creation with the correct check.
END $$;

-- 4. TABLA DE GALERIA
CREATE TABLE IF NOT EXISTS public.galeria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    domain TEXT,
    image_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Asegurar columna domain en galeria
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='galeria' AND column_name='domain') THEN
        ALTER TABLE public.galeria ADD COLUMN domain TEXT;
    END IF;
END $$;

-- 4.5 TABLA DE ACCESO DE DESARROLLADORES
CREATE TABLE IF NOT EXISTS public.developer_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    owner_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(developer_id, owner_id)
);

-- 5. TABLA DE PROMOCIONES
CREATE TABLE IF NOT EXISTS public.promos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    domain TEXT,
    event_type TEXT NOT NULL,
    image_url TEXT,
    start_date DATE,
    end_date DATE,
    display_mode TEXT DEFAULT 'popup',
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, event_type)
);

-- Asegurar columnas en promos
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='promos' AND column_name='domain') THEN
        ALTER TABLE public.promos ADD COLUMN domain TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='promos' AND column_name='display_mode') THEN
        ALTER TABLE public.promos ADD COLUMN display_mode TEXT DEFAULT 'popup';
    END IF;
END $$;

-- 6. HABILITAR RLS
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.galeria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promos ENABLE ROW LEVEL SECURITY;

-- 7. POLÍTICAS DE RLS (USUARIOS)
DROP POLICY IF EXISTS "Public profile view" ON public.usuarios;
CREATE POLICY "Public profile view" ON public.usuarios FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Self manage profile" ON public.usuarios;
CREATE POLICY "Self manage profile" ON public.usuarios FOR ALL USING (auth.uid() = id);

DROP POLICY IF EXISTS "Admin full access users" ON public.usuarios;
CREATE POLICY "Admin full access users" ON public.usuarios FOR ALL USING (public.check_is_admin());

-- 8. POLÍTICAS DE RLS (GALERIA)
DROP POLICY IF EXISTS "Public gallery view" ON public.galeria;
CREATE POLICY "Public gallery view" ON public.galeria FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Owner manage gallery" ON public.galeria;
CREATE POLICY "Owner manage gallery" ON public.galeria FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admin full access gallery" ON public.galeria;
CREATE POLICY "Admin full access gallery" ON public.galeria FOR ALL USING (public.check_is_admin());

-- 9. POLÍTICAS DE RLS (PROMOS)
DROP POLICY IF EXISTS "Public promo view" ON public.promos;
CREATE POLICY "Public promo view" ON public.promos FOR SELECT USING (is_active = TRUE);

DROP POLICY IF EXISTS "Owner manage promos" ON public.promos;
CREATE POLICY "Owner manage promos" ON public.promos FOR ALL USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admin full access promos" ON public.promos;
CREATE POLICY "Admin full access promos" ON public.promos FOR ALL USING (public.check_is_admin());

-- 9.5 POLÍTICAS DE RLS (DEVELOPER ACCESS)
ALTER TABLE public.developer_access ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Developers view their access" ON public.developer_access;
CREATE POLICY "Developers view their access" ON public.developer_access FOR SELECT USING (auth.uid() = developer_id);

DROP POLICY IF EXISTS "Admin full access developer_access" ON public.developer_access;
CREATE POLICY "Admin full access developer_access" ON public.developer_access FOR ALL USING (public.check_is_admin());

-- 10. CONFIGURAR USUARIO ADMIN ESPECÍFICO
DO $$
DECLARE
    target_user_id UUID;
    user_email TEXT := 'francisco.menutech@gmail.com';
BEGIN
    -- Buscar el ID en auth.users
    SELECT id INTO target_user_id FROM auth.users WHERE email = user_email;

    IF target_user_id IS NOT NULL THEN
        -- Asegurar que el perfil exista en public.usuarios y sea Admin
        INSERT INTO public.usuarios (id, name, email, role)
        VALUES (target_user_id, 'Francisco', user_email, 'Admin')
        ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, role = 'Admin';

        RAISE NOTICE 'Usuario % promovido a Admin correctamente.', user_email;
    ELSE
        RAISE NOTICE 'El usuario % no existe en auth.users. Debe registrarse primero.', user_email;
    END IF;
END $$;
