-- ==========================================================
-- TRAGALERO: TABLA DE CONOCIMIENTO Y PREGUNTAS FRECUENTES (FAQS) PARA IA
-- ==========================================================

/*
INSTRUCCIONES:
1. Copia y pega este script en tu panel de Supabase -> SQL Editor.
2. Haz clic en 'Run' para ejecutarlo.
3. Esto creará la tabla 'tragalero_knowledge' para almacenar la información
   del negocio, FAQs y datos de entrenamiento que la IA utilizará para responder.
*/

CREATE TABLE IF NOT EXISTS public.tragalero_knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    category TEXT DEFAULT 'faq', -- 'faq', 'business_info', 'policy', 'service'
    title TEXT NOT NULL,         -- Pregunta o Tema principal
    content TEXT NOT NULL,       -- Respuesta o Detalle explícito
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.tragalero_knowledge ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso
DROP POLICY IF EXISTS "Public and authenticated read tragalero knowledge" ON public.tragalero_knowledge;
CREATE POLICY "Public and authenticated read tragalero knowledge" ON public.tragalero_knowledge
    FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Owner and Admin manage tragalero knowledge" ON public.tragalero_knowledge;
CREATE POLICY "Owner and Admin manage tragalero knowledge" ON public.tragalero_knowledge
    FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- Habilitar Realtime para conocimiento (Idempotente)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        IF NOT EXISTS (
            SELECT 1 FROM pg_publication_tables
            WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'tragalero_knowledge'
        ) THEN
            ALTER PUBLICATION supabase_realtime ADD TABLE public.tragalero_knowledge;
        END IF;
    END IF;
END $$;
