-- ==========================================================
-- TRAGALERO: TABLA DE TAREAS Y SOLICITUDES DEL CHATBOT CON IA
-- ==========================================================

/*
INSTRUCCIONES:
1. Copia y pega este script en tu panel de Supabase -> SQL Editor.
2. Haz clic en 'Run' para ejecutarlo.
3. Esto creará la tabla 'tragalero_tasks' para almacenar solicitudes del Chatbot
   (ej. publicaciones de Facebook, cambios de diseño, solicitudes CS).
*/

CREATE TABLE IF NOT EXISTS public.tragalero_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    client_name TEXT,
    client_domain TEXT,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    due_date TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'Pendiente', -- 'Pendiente', 'En Proceso', 'Completada', 'Cancelada'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.tragalero_tasks ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso
DROP POLICY IF EXISTS "Public insert tragalero tasks" ON public.tragalero_tasks;
CREATE POLICY "Public insert tragalero tasks" ON public.tragalero_tasks
    FOR INSERT WITH CHECK (TRUE);

DROP POLICY IF EXISTS "Owner and Admin manage tragalero tasks" ON public.tragalero_tasks;
CREATE POLICY "Owner and Admin manage tragalero tasks" ON public.tragalero_tasks
    FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- Habilitar Realtime para tareas (Idempotente)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        IF NOT EXISTS (
            SELECT 1 FROM pg_publication_tables
            WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'tragalero_tasks'
        ) THEN
            ALTER PUBLICATION supabase_realtime ADD TABLE public.tragalero_tasks;
        END IF;
    END IF;
END $$;
