-- ==========================================================
-- TRAGALERO: TABLAS Y POLÍTICAS PARA TICKETS E IMPRESORAS
-- ==========================================================

/*
INSTRUCCIONES:
1. Ve a tu panel de Supabase -> SQL Editor.
2. Copia y pega el contenido de este archivo y haz clic en 'Run'.
3. Esto creará las tablas tragalero_tickets, menutech_tickets y tragalero_printers con RLS y Realtime.
*/

-- 1. TABLA PARA CONFIGURACIÓN DE TICKETS DE IMPRESIÓN
CREATE TABLE IF NOT EXISTS public.tragalero_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE UNIQUE,
    domain TEXT,
    config JSONB DEFAULT '{"header_text": "TRAGALERO", "footer_text": "¡Gracias por su compra!", "show_logo": true, "logo_url": null}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.menutech_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE UNIQUE,
    domain TEXT,
    config JSONB DEFAULT '{"header_text": "MENUTECH", "footer_text": "¡Gracias por su compra!", "show_logo": true, "logo_url": null}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABLA PARA IMPRESORAS CONECTADAS POR ETHERNET/RED
CREATE TABLE IF NOT EXISTS public.tragalero_printers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    name TEXT NOT NULL DEFAULT 'Impresora Principal',
    ip TEXT NOT NULL,
    port INT DEFAULT 9100,
    status TEXT DEFAULT 'online',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.tragalero_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menutech_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tragalero_printers ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS
DROP POLICY IF EXISTS "Public view tragalero_tickets" ON public.tragalero_tickets;
CREATE POLICY "Public view tragalero_tickets" ON public.tragalero_tickets FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Owner manage tragalero_tickets" ON public.tragalero_tickets;
CREATE POLICY "Owner manage tragalero_tickets" ON public.tragalero_tickets FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

DROP POLICY IF EXISTS "Owner manage tragalero_printers" ON public.tragalero_printers;
CREATE POLICY "Owner manage tragalero_printers" ON public.tragalero_printers FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- 4. ACTIVAR REALTIME
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
        IF NOT EXISTS (
            SELECT 1 FROM pg_publication_tables
            WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'tragalero_tickets'
        ) THEN
            ALTER PUBLICATION supabase_realtime ADD TABLE public.tragalero_tickets;
        END IF;

        IF NOT EXISTS (
            SELECT 1 FROM pg_publication_tables
            WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'tragalero_printers'
        ) THEN
            ALTER PUBLICATION supabase_realtime ADD TABLE public.tragalero_printers;
        END IF;
    END IF;
END $$;
