-- ==========================================================
-- TRAGALERO: TABLA DE CONFIGURACIÓN DE PAGOS EN LÍNEA Y ÓRDENES
-- ==========================================================

/*
INSTRUCCIONES:
1. Ve a tu panel de Supabase -> SQL Editor.
2. Copia y pega todo el contenido de este archivo y haz clic en 'Run'.
3. Las credenciales de Stripe y Mercado Pago se guardan de forma privada por usuario (user_id).
*/

-- 1. TABLA PARA CONFIGURACIÓN DE PAGOS EN LÍNEA POR CLIENTE
CREATE TABLE IF NOT EXISTS public.tragalero_payment_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE UNIQUE,

    -- Stripe Connect / Direct Credentials
    stripe_account_id TEXT,
    stripe_publishable_key TEXT,
    stripe_secret_key TEXT,
    stripe_enabled BOOLEAN DEFAULT FALSE,
    stripe_status TEXT DEFAULT 'disconnected', -- disconnected, connected, active

    -- Mercado Pago OAuth / Credentials
    mercadopago_user_id TEXT,
    mercadopago_public_key TEXT,
    mercadopago_access_token TEXT,
    mercadopago_enabled BOOLEAN DEFAULT FALSE,
    mercadopago_status TEXT DEFAULT 'disconnected', -- disconnected, connected, active

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. ASEGURAR COLUMNAS DE ESTADO DE PAGO EN TRAGALERO_ORDERS
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending'; -- pending, approved, rejected, cancelled
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS payment_id TEXT;
ALTER TABLE public.tragalero_orders ADD COLUMN IF NOT EXISTS payment_provider TEXT; -- cash, transfer, stripe, mercadopago

ALTER TABLE public.menutech_orders ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending';
ALTER TABLE public.menutech_orders ADD COLUMN IF NOT EXISTS payment_id TEXT;
ALTER TABLE public.menutech_orders ADD COLUMN IF NOT EXISTS payment_provider TEXT;

-- 3. HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.tragalero_payment_config ENABLE ROW LEVEL SECURITY;

-- 4. POLÍTICAS DE ACCESO
DROP POLICY IF EXISTS "Public view payment enabled flags" ON public.tragalero_payment_config;
CREATE POLICY "Public view payment enabled flags" ON public.tragalero_payment_config
    FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Owner manage payment config" ON public.tragalero_payment_config;
CREATE POLICY "Owner manage payment config" ON public.tragalero_payment_config
    FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());
