-- ==========================================================
-- TRAGALERO: TABLAS DE TEMPLATES, MENÚS Y ÓRDENES
-- ==========================================================

/*
INSTRUCCIONES:
1. Ve a tu panel de Supabase -> SQL Editor.
2. Copia y pega todo el contenido de este archivo y haz clic en 'Run'.
3. Ve a la sección 'Database' -> 'Publications' -> 'supabase_realtime'
   y asegúrate de habilitar la tabla 'menutech_orders' para actualizaciones en tiempo real.
*/

-- 1. TABLA PARA PLANTILLAS WEB (adminTemplate.html)
CREATE TABLE IF NOT EXISTS public.menutech_web_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE UNIQUE,
    config JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABLA PARA MENÚS DIGITALES (adminMenus.html / menu.html)
CREATE TABLE IF NOT EXISTS public.menutech_menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE UNIQUE,
    domain TEXT,
    slug TEXT UNIQUE,
    menu_style TEXT DEFAULT 'mode2',
    cover_url TEXT,
    cover_type TEXT DEFAULT 'image',
    config JSONB DEFAULT '{"categories": [], "toppings": []}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABLA PARA ÓRDENES EN TIEMPO REAL (adminOrders.html)
CREATE TABLE IF NOT EXISTS public.menutech_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    client_name TEXT,
    client_phone TEXT,
    client_address TEXT,
    items JSONB DEFAULT '[]'::jsonb,
    total NUMERIC(10,2) DEFAULT 0,
    status TEXT DEFAULT 'pending', -- pending, in_progress, completed, cancelled
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TABLA PARA MENÚS FÍSICOS (physicalMenu.html)
CREATE TABLE IF NOT EXISTS public.menutech_physical_menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    template_id TEXT,
    layout_config JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, template_id)
);

-- 5. HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.menutech_web_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menutech_menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menutech_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menutech_physical_menus ENABLE ROW LEVEL SECURITY;

-- 6. POLÍTICAS DE ACCESO PÚBLICO / PROPIETARIO

-- Web Templates
DROP POLICY IF EXISTS "Public web templates view" ON public.menutech_web_templates;
CREATE POLICY "Public web templates view" ON public.menutech_web_templates FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Owner manage web templates" ON public.menutech_web_templates;
CREATE POLICY "Owner manage web templates" ON public.menutech_web_templates FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- Menús Digitales
DROP POLICY IF EXISTS "Public menus view" ON public.menutech_menus;
CREATE POLICY "Public menus view" ON public.menutech_menus FOR SELECT USING (TRUE);

DROP POLICY IF EXISTS "Owner manage menus" ON public.menutech_menus;
CREATE POLICY "Owner manage menus" ON public.menutech_menus FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- Órdenes
DROP POLICY IF EXISTS "Public insert orders" ON public.menutech_orders;
CREATE POLICY "Public insert orders" ON public.menutech_orders FOR INSERT WITH CHECK (TRUE);

DROP POLICY IF EXISTS "Owner manage orders" ON public.menutech_orders;
CREATE POLICY "Owner manage orders" ON public.menutech_orders FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- Menús Físicos
DROP POLICY IF EXISTS "Owner manage physical menus" ON public.menutech_physical_menus;
CREATE POLICY "Owner manage physical menus" ON public.menutech_physical_menus FOR ALL USING (auth.uid() = user_id OR public.check_is_admin());

-- 7. ACTIVAR REALTIME PARA ÓRDENES
ALTER PUBLICATION supabase_realtime ADD TABLE public.menutech_orders;
